clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x86_64

cache:
  - "C:\\SR"
  - .stack-work

environment:
  matrix:
    - GHCVER: 8.4.4

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y haskell-stack
  - stack setup
  - stack exec -- pacman --noconfirm -S make
  - refreshenv

before_build:
  - stack --version

build_script:
  - stack build

before_package:
  - mv "$(stack path --local-install-root)/bin/*.exe" .

deploy:
  description: "Release description"
  provider: GitHub
  auth_token:
    secure: S/xfkviXL/1CCRkqnYt31xNbr7AV9KKjUdiaDswt6ly++9yQskxRZnPo84ofnfDi
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only
