[package]
name = "drahko/drahko"
version = "0.0.1"
authors = [
  "Nikita Tchayka <nick@booster.cloud>"
]
description = "A modern Windows automation suite"
homepage = "https://drahko.github.io"
repository = "https://github.com/drahko/drahko"

[dependencies]

[targets.lib]
path = "lib"
mods = [
  "Drahko",
  "Drahko.Builtins",
  "Drahko.FFI",
]